### ISSUE TITLE
getting Error

### ISSUE THREAD

**Issue by himadrinath** [kamarouski/messenger-client#1]
@kamarouski   i added in my (.NETCoreApp,Version=v1.0) project. and getting this error

![fbbot](https://cloud.githubusercontent.com/assets/12247490/17396645/f5336dbc-5a51-11e6-8b5d-3188a114525b.png)

**Comment by akomio** [comment]
I'll publish the new version today. It will fix this reference error.

**Comment by kamarouski** [comment]
I'll publish the new version today with this problem fixed.

**Comment by himadrinath** [comment]
thank you. i really appreciate it

**Comment by kamarouski** [comment]
Please update to the latest version. Should be fine now.

**Comment by himadrinath** [comment]
many many thanks. if i have more question about bot. can i tweet u?

**Comment by kamarouski** [comment]
@himadrinath sure
