### ISSUE TITLE
Won't install on .NET Framework v4.6.1

### ISSUE THREAD

**Issue by prdufresne** [kamarouski/messenger-client#2]
Trying to install the package in a C# .NET application but I keep getting the following error even though it seems it should work on Microsoft .NET >=1.0.0.

Error		Could not install package 'Messenger.Client 0.2.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by kamarouski** [comment]
@prdufresne The package doesn't support net461 at the moment. 

I'll release the new version over the weekend make it based on Standard Library. This will solve this error.
