### ISSUE TITLE
Won't install on 4.6.2

### ISSUE THREAD

**Issue by todd-herbert** [kamarouski/messenger-client#4]
I'm getting the following error:

Could not install package 'Messenger.Client 0.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by kamarouski** [comment]
@todd-herbert It's currently supports .NET Core only (.NET Standard Library 1.6)
